### ISSUE TITLE
ModuleNotFoundError: No module named 'wcwidth'

### ISSUE THREAD

**Issue by dynect** [Rockhopper-Technologies/enlighten#14]
I'm getting an error when trying to use enlighten. The install goes fine:
```
$ pip install enlighten
Collecting enlighten
  Downloading enlighten-1.4.0-py2.py3-none-any.whl (36 kB)
Collecting blessed>=1.16.1
  Downloading blessed-1.17.2-py2.py3-none-any.whl (76 kB)
     |████████████████████████████████| 76 kB 3.9 MB/s 
Requirement already satisfied: wcwidth>=0.1.4 in ./Library/Python/3.6/lib/python/site-packages (from blessed>=1.16.1->enlighten) (0.1.7)
Requirement already satisfied: six>=1.9.0 in /opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from blessed>=1.16.1->enlighten) (1.14.0)
Installing collected packages: blessed, enlighten
Successfully installed blessed-1.17.2 enlighten-1.4.0
```
Although upon importing the module I get:
```
$ python -c 'import enlighten; print(enlighten.__version__)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/enlighten/__init__.py", line 14, in <module>
    from enlighten.counter import Counter, SubCounter
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/enlighten/counter.py", line 18, in <module>
    from enlighten._manager import get_manager
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/enlighten/_manager.py", line 26, in <module>
    from enlighten._terminal import Terminal
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/enlighten/_terminal.py", line 14, in <module>
    from blessed import Terminal as _Terminal
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/blessed/__init__.py", line 12, in <module>
    from blessed.terminal import Terminal
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/blessed/terminal.py", line 27, in <module>
    from .sequences import Termcap, Sequence, SequenceTextWrapper
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/blessed/sequences.py", line 11, in <module>
    import wcwidth
ModuleNotFoundError: No module named 'wcwidth'
```
Here's a similar error from `blessed`:
```
$ python -c 'import blessed; print(blessed.__version__)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/blessed/__init__.py", line 12, in <module>
    from blessed.terminal import Terminal
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/blessed/terminal.py", line 27, in <module>
    from .sequences import Termcap, Sequence, SequenceTextWrapper
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/blessed/sequences.py", line 11, in <module>
    import wcwidth
ModuleNotFoundError: No module named 'wcwidth'
```

**Comment by avylove** [comment]
This looks like a path issue. Notice pip is finding wcwidth in `./Library/Python/3.6/lib/python/site-packages` and six in `/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages` You may just want to force an install of wcwidth.

**Comment by dynect** [comment]
Hello,

Yes I noticed that as well. 

I'm not sure where that path is set, or why exactly it's set like that. Any ideas?

**Comment by avylove** [comment]
Not sure, but glad it's working. Going to go ahead and close this.
