### ISSUE TITLE
Signal not allowed in Thread

### ISSUE THREAD

**Issue by SKnight79** [Rockhopper-Technologies/enlighten#59]
Got this when trying to add a counter to a manager. Any advice on this? 

Exception in thread Thread-11 (create):
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "[redacted]", line [redacted], in [redacted]
    counter = self.progress_manager.counter(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/enlighten/_basemanager.py", line 154, in counter
    return self._add_counter(self.counter_class, position=position, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/enlighten/_basemanager.py", line 285, in _add_counter
    self._set_scroll_area()
  File "/opt/homebrew/lib/python3.11/site-packages/enlighten/_manager.py", line 182, in _set_scroll_area
    signal.signal(signal.SIGWINCH, self._stage_resize)
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/signal.py", line 56, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: signal only works in main thread of the main interpreter

**Comment by avylove** [comment]
That's the resize handler being set. Either move that logic to the main thread or disable resizing by passing `no_resize` when creating the manager.

**Comment by SKnight79** [comment]
done and done. works like a charm!
